- crates/yttrium/src/bundler/client.rs
- crates/yttrium/src/bundler/pimlico/client.rs
- crates/yttrium/src/bundler/pimlico/paymaster/client.rs
- crates/yttrium/src/jsonrpc.rs
- crates/yttrium/src/transaction/send/safe_test.rs
- crates/yttrium/src/transaction/send/simple_account_test.rs
Fixes test flakiness due to hardcoded delay. Seems we were doing the same operation twice (once 1 time and second in a polling operation), so removed the redundant one. Needed to tweak the types a little.
> chore: fix arbitrary test delay

- crates/yttrium/src/transaction/send/safe_test.rs
Fixes the `AA24 signature error error` to result in what appears to be a successful Safe deployment w/ initial transaction.
> fix: Safe MVP now working

- crates/yttrium/Cargo.toml
- crates/yttrium/src/bundler/pimlico/paymaster/models.rs
- crates/yttrium/src/entry_point.rs
- crates/yttrium/src/entry_point/get_sender_address.rs
- crates/yttrium/src/smart_accounts/nonce.rs
- crates/yttrium/src/smart_accounts/safe.rs
- crates/yttrium/src/transaction/send/safe_test.rs
- crates/yttrium/src/transaction/send/simple_account_test.rs
Adds test coverage for transferring native token balance from the smart account to another account. It does this transfer twice, the first time as part of the account deployment, and the second against the deployed account.
This fixes some issues in the process:
- Sponsor transaction should have `undefined` `factory` and `factoryData` when working against a deployed account
- Switch to manual `CREATE2` implementation as `getSenderAddress()` only works when the account isn't yet deployed
- General code refactors and cleanup
> fix: balance transfer & deployed txn

- crates/ffi/build-rust-ios.sh
- crates/ffi/build.rs
- Removes the force install of `swift-bridge-cli` to optimize speed of devloop
- Reruns the generation of Swift bindings if they are deleted
> chore: improve Swift build

- Cargo.toml
Reduces the .so file size for Android architectures:
- for arm64: from 11.7 mb to 6.4 mb
- for armv7: from 8.2 mb to 4.5 mb
> Add profile.release

- crates/yttrium/src/bundler/models/user_operation_receipt.rs
This PR changed the `entryPoint` field of the receipt structure to become optional since the Pimlico response doesn't have it and resulted in an error: `Deserialization error: missing field: entryPoint`.
Tested by https://github.com/reown-com/blockchain-api/pull/824
> fix: making entryPoint optional

- crates/kotlin-ffi/Cargo.toml
- crates/yttrium/src/bundler/client.rs
Changes the decode type of `eth_getUserOperationReceipt` to support `null` (via `Option`). This seems to be what Pimlico returns for the first several seconds.
Also adjusts internal code `wait_for_user_operation_receipt()` to test this. Errors will no longer be retried, only `null` response.
[Slack conversation](https://reown-inc.slack.com/archives/C03SCF66K2T/p1730728557150829)
> fix: null user op receipt error

- crates/ffi/Cargo.toml
- crates/ffi/YttriumCore/Sources/YttriumCore/SwiftFFI/Error/Erc6492.swift
- crates/ffi/YttriumCore/Sources/YttriumCore/ffi.swift
- crates/ffi/src/account_client.rs
- crates/ffi/src/erc6492_client.rs
- crates/ffi/src/error.rs
- crates/ffi/src/lib.rs
- crates/yttrium/src/account_client.rs
- crates/yttrium/src/transaction/send/safe_test.rs
- justfile
- test/scripts/forked_state/docker-compose.yaml
Adds ERC-6492 signature verification to the Swift FFI bindings
Resolves RES-93
Depends on https://github.com/reown-com/erc6492/pull/3
> feat: ERC-6492 signature verification

- crates/yttrium/src/account_client.rs
- crates/yttrium/src/transaction/send/safe_test.rs
`get_address()` was still using the legacy signer implementation. This PR removes that
> fix: account address input source

- crates/yttrium/Cargo.toml
- crates/yttrium/src/chain_abstraction/api/mod.rs
- crates/yttrium/src/chain_abstraction/api/route.rs
- crates/yttrium/src/chain_abstraction/api/status.rs
- crates/yttrium/src/chain_abstraction/client.rs
- crates/yttrium/src/chain_abstraction/error.rs
- crates/yttrium/src/chain_abstraction/mod.rs
- crates/yttrium/src/lib.rs
Adds client + types for chain abstraction.
In subsequent PRs:
> feat: chain abstraction client

- crates/yttrium/src/chain_abstraction/api/route.rs
This PR changes the chain orchestrator's `NotBridgingRequired` `_field` to the `transactions` and makes it public to allow the construct of the type.
> fix: `NotBridgingRequired` transactions field name and visibility

- crates/yttrium/src/chain_abstraction/api/route.rs
This PR adds the `bridging_fee` amount to the funding metadata.
> feat(CA client): adding bridging fee

- crates/kotlin-ffi/src/lib.rs
- crates/yttrium/src/chain_abstraction/api/prepare.rs
- crates/yttrium/src/chain_abstraction/client.rs
- crates/yttrium/src/chain_abstraction/error.rs
- crates/yttrium/src/chain_abstraction/tests.rs
- crates/yttrium/src/chain_abstraction/ui_fields.rs
Adds a WIP `prepare_detailed()` (for https://linear.app/reown/issue/WK-389/use-yttrium-for-txn-sending-1-function-prepare) and also does some remaining renames from `route()` -> `prepare()`
Depends on https://github.com/reown-com/yttrium/pull/101
> chore: some renames & wip prepare_detailed()

- .github/workflows/ci.yml
- .github/workflows/release-dart.yml
- .github/workflows/release-kotlin.yml
- .gitignore
- .jitpack.yml
- Cargo.toml
- README.md
- benchmark-profile-output-sizes.sh
- crates/kotlin-ffi/uniffi.toml
- crates/yttrium/src/examples/eip7702_smart_sessions.rs
- crates/yttrium/src/smart_accounts/safe.rs
- crates/yttrium/src/transaction_sponsorship/mod.rs
- crates/yttrium/src/transaction_sponsorship/tests.rs
- crates/yttrium/src/uniffi_compat.rs
- crates/yttrium_dart/generate_android_lib.sh
- crates/yttrium_dart/generate_ios_lib.sh
- crates/yttrium_dart/lib/generated/frb_generated.dart
- generate_kotlin_locally.sh
- justfile
- scripts/build-xcframework.sh
- Rename the profile bindings are generated with from `release` to `uniffi-release`
- Add various other profiles with various configurations
- Add script to test all of these profiles and record the results in a CSV
https://docs.google.com/spreadsheets/d/1Ko7TmIbNrgB2PWN8cPDM4GL6Iy2d8c-VrD0FnQ9SicI/edit?gid=21763173#gid=21763173
From the above sheet:
- Short-term goal is `profile7-nightly-stdopt`, but we may hit issues
- Long-term we may be able to achieve `profile9-nightly-stdopt`, but it requires us to be very careful with our panics and it makes debugging them much more difficult
> chore: benchmark profiles

- Cargo.lock
- crates/yttrium/Cargo.toml
- crates/yttrium/src/bundler/client.rs
- crates/yttrium/src/chain_abstraction/client.rs
- crates/yttrium/src/chain_abstraction/pulse.rs
- crates/yttrium/src/chain_abstraction/send_transaction.rs
- crates/yttrium/src/chain_abstraction/tests.rs
- crates/yttrium/src/serde.rs
- crates/yttrium/src/test_helpers/mod.rs
Adds compatibility for `Instant` and `SystemTime` on wasm targets
[Slack conversation](https://reown-inc.slack.com/archives/C07HQ8RCGD8/p1739368853019669?thread_ts=1739366533.563759&cid=C07HQ8RCGD8)
> fix: wasm time

- .github/workflows/release-dart.yml
- See: https://reown-inc.slack.com/archives/C07HQ8RCGD8/p1740049847785069
> ci: use `macos-14` instead of expensive `macos-latest-xlarge`

- crates/yttrium/src/chain_abstraction/client.rs
Adds more parameter assertions for checking that transaction signatures are correct. This is a panic because it indicates an implementation problem with the wallet and should be caught during development.
This is in-response to issues implementing sample wallets that incorrectly sign the transaction, but get confusing and hard-to-debug gas-related errors. By pre-validating the signatures here we can catch the issue earlier and provide a better error message to developers.
Resolves WK-573
> fix: verify sigs

- crates/yttrium/src/chain_abstraction/api/prepare.rs
- crates/yttrium/src/chain_abstraction/tests.rs
This PR extends Chain Abstraction `PrepareResponseError` with the new `reason` field to contain an error message/description addition to the error type.
This change is a dependency of https://github.com/reown-com/blockchain-api/pull/976
> feat(CA): extending an error object with the `reason` field

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- Cargo.lock
- README.md
- crates/yttrium/Cargo.toml
- crates/yttrium/src/chain_abstraction/api/prepare.rs
- crates/yttrium/src/chain_abstraction/error.rs
- crates/yttrium/src/chain_abstraction/send_transaction.rs
- crates/yttrium/src/chain_abstraction/solana/mod.rs
- crates/yttrium/src/chain_abstraction/solana/tests.rs
- crates/yttrium/src/chain_abstraction/tests.rs
- crates/yttrium/src/provider_pool.rs
- crates/yttrium/src/wallet_service_api.rs
- justfile
Resolves WK-608
Resolves WK-605
Resolves WK-611
> fix: various fixes

- crates/yttrium/src/chain_abstraction/api/prepare.rs
This PR adds a new `AssetNotSupported` error type for cases where we know that the initial transaction will fail (insufficient balance), but the possible funding asset is not supported for bridging.
The full context: https://reown-inc.slack.com/archives/C0816SK4877/p1741702145995839
> feat(CA): adding `AssetNotSupported` error type

- crates/kotlin-ffi/src/lib.rs
- crates/yttrium/src/chain_abstraction/client.rs
- crates/yttrium/src/uniffi_compat.rs
- crates/yttrium/src/wallet_service_api.rs
Adds ability for sample wallets to easily call `wallet_getAssets`
Resolves WK-646
[Slack conversation](https://reown-inc.slack.com/archives/C0816SK4877/p1743608035139049)
> feat: wallet_getAssets

- crates/yttrium/src/chain_abstraction/api/prepare.rs
- crates/yttrium/src/chain_abstraction/client.rs
- crates/yttrium/src/chain_abstraction/solana/tests.rs
Adds `same_kind_as()` helper function to help https://github.com/reown-com/blockchain-api/pull/1035
> feat: Eip155OrSolanaAddressKind

- crates/yttrium/src/chain_abstraction/api/prepare.rs
This PR adds a new `TransactionSimulationFailed` error type for the Chain Abstraction route response.
This will properly handle cases where the broken initial transaction was pushed to the route, and we know that the transaction will fail when we are making a simulation for getting asset changes.
> feat(CA): adding `TransactionSimulationFailed` error type

- crates/yttrium/src/sign/mod.rs
Added `pair_json` and `approve_json` methods on Rust side to be used specifically by Flutter SDK to avoid mappings boilerplate
Added `self_public_key` in `approve` response as both web and flutter responds with a complete Session object after approval that includes self_public_key. Before introducing rust client this was generated on core on the specific platform but now self_public_key is generated on rust side.
Web: https://github.com/WalletConnect/walletconnect-monorepo/blob/494a945678d44df55162cf37bdbb9e80a6a35b1d/packages/sign-client/src/controllers/engine.ts#L444
Flutter: https://github.com/reown-com/reown_flutter/blob/2192103999db0bb3482f624d20df727ec7fa0213/packages/reown_sign/lib/sign_engine.dart#L355
> Add self_public_key to Session after Approval
