crates/ffi/src/account_client.rs
crates/ffi/src/lib.rs
crates/yttrium/src/account_client.rs
crates/yttrium/src/transaction/send.rs
crates/yttrium/src/transaction/send/safe_test.rs
platforms/swift/Sources/Yttrium/AccountClient.swift
platforms/swift/Sources/Yttrium/AccountClient7702.swift
platforms/swift/Sources/Yttrium/AccountClientProtocol.swift

Refactor to support calling from Swift
Related: https://github.com/reown-com/reown-swift/pull/6

chore: Safe Swift refactor

---

crates/yttrium/src/transaction/send/safe_test.rs

Fixes batch transactions
Adds tests for batch transactions & no transactions (just deploy UserOps)

fix: safe batch transactions

---

crates/yttrium/src/bundler/models/user_operation_receipt.rs
crates/yttrium/src/chain.rs
crates/yttrium/src/smart_accounts/safe.rs
crates/yttrium/src/smart_accounts/simple_account/sender_address.rs
crates/yttrium/src/transaction/send.rs
crates/yttrium/src/transaction/send/safe_test.rs
crates/yttrium/src/transaction/send/simple_account_test.rs

- Fix Safe bricking issue
- Tests pick chain ID automatically based on RPC provider's chain
- More robust type for user op hash

fix: Safe bricking

---

crates/yttrium/Cargo.toml
crates/yttrium/src/bundler/client.rs
crates/yttrium/src/bundler/pimlico/paymaster/client.rs

To debug response deserialization in Blockchain API

fix: change printlns to proper logging & log sendUserOperation response

---

crates/yttrium/src/erc7579/smart_sessions/mod.rs

Needed by https://github.com/reown-com/blockchain-api/pull/820

fix: updated isPermissionEnabled

---

Cargo.toml
crates/ffi/Cargo.toml
crates/ffi/src/account_client.rs
crates/kotlin-ffi/src/lib.rs
crates/yttrium/Cargo.toml
crates/yttrium/src/signer.rs
crates/yttrium/src/transaction/send/safe_test.rs
crates/yttrium/src/user_operation.rs

Depends on https://github.com/reown-com/erc6492/pull/7

feat: bump alloy

---

crates/yttrium/src/chain_abstraction/client.rs

Attempting to debug: https://reown-inc.slack.com/archives/C07HQ8RCGD8/p1731949966730559

fix: capture decoding error

---

crates/yttrium/src/chain_abstraction/api/route.rs

This PR adds initial transaction transfer metadata schema.

feat: adding initial transaction transfer metadata

---

README.md
crates/yttrium/Cargo.toml
crates/yttrium/src/chain_abstraction/api/route.rs
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/entry_point.rs
crates/yttrium/src/erc7579/accounts/mod.rs
crates/yttrium/src/erc7579/accounts/safe.rs
crates/yttrium/src/erc7579/addresses.rs
crates/yttrium/src/erc7579/mod.rs
crates/yttrium/src/erc7579/ownable_validator.rs
crates/yttrium/src/erc7579/smart_sessions.rs
crates/yttrium/src/examples/eip7702.rs
crates/yttrium/src/smart_accounts/safe.rs
crates/yttrium/src/transaction/send/safe_test.rs
justfile

Working 7702 smart sessions demo
Based off: https://github.com/rhinestonewtf/module-sdk-tutorials/blob/main/src/smart-sessions/permissionless-safe-7702.ts
Fixes RES-156
Fixes RES-119

feat: 7702 working

---

crates/kotlin-ffi/src/lib.rs
crates/yttrium/src/chain_abstraction/client.rs
crates/yttrium/src/chain_abstraction/mod.rs
crates/yttrium/src/chain_abstraction/route_ui_fields.rs
crates/yttrium/src/chain_abstraction/tests.rs
platforms/swift/Sources/Yttrium/yttrium.swift

Adds a test case that some (based on real case) raw input will compute the right amounts and final RouteUiFields value. Based on [this Slack conversation]()https://reown-inc.slack.com/archives/C0816SK4877/p1734024919992679?thread_ts=1733907929.789279&cid=C0816SK4877

chore: test get_route_ui_fields

---

Cargo.toml
crates/ffi/Cargo.toml
crates/kotlin-ffi/Cargo.toml
crates/yttrium/Cargo.toml
crates/yttrium_dart/rust/Cargo.toml

Did a quick pass and removed as many features as I could. Everything still seems to work and CI passes so...
Fixes RES-112

chore: reduce features

---

.github/workflows/ci.yml
crates/kotlin-ffi/src/lib.rs
crates/yttrium/src/chain_abstraction/api/mod.rs
crates/yttrium/src/chain_abstraction/api/prepare.rs
crates/yttrium/src/chain_abstraction/client.rs
crates/yttrium/src/chain_abstraction/mod.rs
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/chain_abstraction/ui_fields.rs
crates/yttrium/src/uniffi_compat.rs
crates/yttrium_dart/lib/generated/frb_generated.dart
crates/yttrium_dart/lib/generated/frb_generated.io.dart
crates/yttrium_dart/lib/generated/lib.dart
crates/yttrium_dart/rust/src/frb_generated.rs
crates/yttrium_dart/rust/src/lib.rs

As per [this discussion](https://reown-inc.slack.com/archives/C0816SK4877/p1734450257216149?thread_ts=1734438668.207979&cid=C0816SK4877), aligning on a better set of method names
Fixes WK-392

chore: route -> prepare

---

crates/yttrium/Cargo.toml
crates/yttrium/src/erc7579/ownable_validator.rs
crates/yttrium/src/erc7579/policy.rs
crates/yttrium/src/erc7579/smart_sessions.rs
crates/yttrium/src/examples/eip7702.rs

Updates smart sessions stuff as per this thread: https://reown-inc.slack.com/archives/C06G97QSSUX/p1735308778115519

fix: smart sessions major changes

---

crates/yttrium/src/examples/eip7702_smart_sessions.rs
crates/yttrium/src/transaction_sponsorship/tests.rs

Adds test coverage for 7702 happy path on Odyssey testnet.
Fixes WK-480

chore: test odyssey

---

.gitignore
Cargo.toml
benchmark.sh
build-wasm.sh
crates/yttrium/Cargo.toml
crates/yttrium/src/chain_abstraction/api/mod.rs
generate_kotlin_locally.sh

Adds benchmarks for the wasm code, and implement size optimizations

chore: benchmark and optimize wasm size

---

Cargo.lock
crates/yttrium/src/chain_abstraction/api/fungible_price.rs
crates/yttrium/src/chain_abstraction/api/prepare.rs
crates/yttrium/src/chain_abstraction/api/status.rs
crates/yttrium/src/chain_abstraction/client.rs
crates/yttrium/src/chain_abstraction/pulse.rs
crates/yttrium/src/provider_pool.rs
crates/yttrium/src/transaction_sponsorship/mod.rs
crates/yttrium/src/transaction_sponsorship/tests.rs

feat: add sessionId, st, sv params to RPC

---

.github/workflows/e2e.yml
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/test_helpers/mod.rs

chore: add E2E tests

---

Cargo.lock
crates/yttrium/src/chain_abstraction/api/prepare.rs
crates/yttrium/src/chain_abstraction/api/status.rs
crates/yttrium/src/chain_abstraction/client.rs
crates/yttrium/src/chain_abstraction/pulse.rs
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/transaction_sponsorship/tests.rs

fix: remove unused package_name param

---

funding.json

temporarily adding a file to verify repo ownership required for a grant process

chore: verify repo ownership

---

crates/yttrium/src/blockchain_api.rs
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/lib.rs
crates/yttrium/src/provider_pool.rs
crates/yttrium/src/wallet_provider.rs
crates/yttrium/src/wallet_service_api.rs

chore: test ERC-7811

---

.github/workflows/e2e.yml
crates/kotlin-ffi/src/lib.rs
crates/yttrium/src/chain_abstraction/api/prepare.rs
crates/yttrium/src/chain_abstraction/client.rs
crates/yttrium/src/chain_abstraction/solana/tests.rs
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/wasm_compat.rs
crates/yttrium_dart/lib/generated/frb_generated.dart
crates/yttrium_dart/lib/generated/frb_generated.io.dart
crates/yttrium_dart/lib/generated/lib.dart
crates/yttrium_dart/rust/src/frb_generated.rs
crates/yttrium_dart/rust/src/lib.rs
justfile
test/scripts/7702/docker-compose.yaml
test/scripts/forked_state/docker-compose.yaml
test/scripts/local_infra/docker-compose.yaml

For https://github.com/reown-com/blockchain-api/pull/1025

feat: LiFi flag

---

.github/workflows/ci.yml
crates/yttrium/src/chain_abstraction/solana/tests.rs
crates/yttrium/src/wallet_service_api.rs
generate_kotlin_locally.sh

Fixes bindings error: [Slack conversation](https://reown-inc.slack.com/archives/C07HQ8RCGD8/p1744277863541609)
Also fixes that CI didn't catch this.

fix(ci): Kotlin CI

---

.github/workflows/e2e.yml
crates/yttrium/src/chain_abstraction/client.rs
crates/yttrium/src/chain_abstraction/solana/tests.rs
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/erc4337/mod.rs
crates/yttrium/src/test_helpers/mod.rs

Fixes issue raised in this [Slack conversation](https://reown-inc.slack.com/archives/C03SCF66K2T/p1744378976546939)
Also fixes yttrium tests

fix: no paymaster in UserOperationReceipt

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
crates/yttrium/Cargo.toml
crates/yttrium/src/uniffi_compat/mod.rs
crates/yttrium/src/uniffi_compat/sui.rs
justfile
test/scripts/forked_state/docker-compose.yaml

feat: SUI wallet utils

---

.github/workflows/ci.yml
crates/yttrium/Cargo.toml
crates/yttrium/src/chain_abstraction/pulse.rs
crates/yttrium/src/chain_abstraction/solana/tests.rs
crates/yttrium/src/chain_abstraction/tests.rs
crates/yttrium/src/provider_pool.rs
crates/yttrium/src/uniffi_compat/mod.rs
crates/yttrium/src/uniffi_compat/sui.rs

feat: SUI balance client

---

.github/workflows/ci.yml
.github/workflows/release-kotlin.yml
Cargo.lock
Cargo.toml
crates/kotlin-ffi/Cargo.toml
crates/kotlin-ffi/android/build.gradle
crates/yttrium/Cargo.toml
crates/yttrium/src/chain_abstraction/solana/tests.rs
crates/yttrium/src/lib.rs
crates/yttrium/src/uniffi_compat/sui.rs
generate_kotlin_locally.sh
justfile
scripts/build-xcframework.sh

[Slack conversation](https://reown-inc.slack.com/archives/C04DB2EAHE3/p1749013632699429?thread_ts=1748944095.512389&cid=C04DB2EAHE3)

fix: SUI transaction signing

---

crates/yttrium/src/sign/readme.md
crates/yttrium/src/sign/relay.rs

[Slack conversation](https://reown-inc.slack.com/archives/C098LHLHCNM/p1758028448128209?thread_ts=1758020865.054139&cid=C098LHLHCNM)

fix incorrect state transition
